package com.example.test.activity

import android.annotation.SuppressLint
import android.os.Bundle
import android.widget.ImageView
import android.widget.TextView
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.recyclerview.widget.LinearLayoutManager
import androidx.recyclerview.widget.RecyclerView
import com.example.test.modelclass.Model_for_topics
import com.example.test.R
import com.example.test.adapterclass.adapter_for_topics

class topics : AppCompatActivity() {
    @SuppressLint("MissingInflatedId")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        enableEdgeToEdge()
        setContentView(R.layout.activity_topics)
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main)) { v, insets ->
            val systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars())
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom)
            insets
        }


        val array= arrayListOf<Model_for_topics>()


        val adapterForTopics= adapter_for_topics(this,array)

        val recyclerView=findViewById<RecyclerView>(R.id.Recycler_topics)
        recyclerView.adapter=adapterForTopics
        recyclerView.layoutManager= LinearLayoutManager(this, LinearLayoutManager.VERTICAL,false)

        //get data from recyclerview of adapterclass
        val data=intent.getStringExtra("data")

        /* val Paragraphs="Paragraphs"
       val Oneline="Oneline"
       val Quiz="Quiz"
       val Trick="Trick"*/

        //these all data for get key from adapter class and Paragraphs and add topics
        if (data=="Paragraphs History"){
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","1","अमेरिका का स्वतंत्रता संग्राम"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","2","फ्रांस की राज्यक्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","3","इटली का एकीकरण"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","4","जर्मनी का एकीकरण"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","5","रूस की क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","6","औद्योगिक क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","7","प्रथम विश्वयुद्ध"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","8","दुसरा विश्व युद्ध"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","9","बंगाल के गवर्नर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","10","भारत के गवर्नर जनरल"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","11","भारत के वायसराय"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","12","महान क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","13","सामाजिक-धार्मिक आंदोलन"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","14","आंदोलन, घटनाएं और वर्ष"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","15","स्वतंत्रता संघर्ष"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","16","प्रमुख वचन और नारे"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","17","गुलाम वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","18","खिलजी वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","19","तुगलक वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","20","धार्मिक आंदोलन"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","21","मराठा साम्राज्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","22","सिख शक्ति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","23","मराठा साम्राज्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","24","सिख शक्ति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","25","बाबर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","26","हुमायूं"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","27","अकबर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","28","जहांगीर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","29","शाहजहां"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","30","औरंगजेब"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","31","हड़प्पा सभ्यता"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","32","वैदिक साहित्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Paragraphs History","33","मौर्य व गुप्त काल"))
        }
        else if (data=="Paragraphs Geography"){
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","1","सौर मंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","2","पृथ्वी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","3","जलमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","4","झीलें"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","5","ज्वार भाटा"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","6","वायुमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","7","पवनें"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","8","पृथ्वी की संरचना"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","9","पस्थलमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","10","ज्वालामुखी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","11","पर्वत"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","12","भूकंप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","13","मरुस्थल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","14","पठार"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","15","एशिया"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","16","अफ्रीका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","17","यूरोप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","18","उत्तरी अमेरिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","19","दक्षिणी अमेरिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","20","ऑस्ट्रेलिया"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","21","अंटार्कटिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","22","विश्व के महासागर"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","23","वभारत का भूगोल सामान्य परिचय"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","24","नदियों के किनारे बसे शहर"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","25","भारत की जलवायु"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","26","भारत की नदियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","27","भारत की मिट्टियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","28","भारत की कृषि"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","29","भारत का भौतिक स्वरूप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","30","अभयारण/ राष्ट्रीय उद्यान"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","31","विश्व की प्रमुख जनजातियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","32","वराज्य और उसकी राजधानी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Paragraphs Geography","33","भारत में खनिज"))

        }
        else if (data=="Paragraphs Constitution"){
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","1","भारत का संवैधानिक इतिहास"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","2","संविधान सभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","3","संविधान की प्रस्तावना"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","4","संविधान की विशेषताएं"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","5","संविधान के स्त्रोत"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","6","संविधान के भाग"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","7","संविधान की अनुसूचियां"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","8","संविधान के अनुच्छेद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","9","संघ और उसके राज्य क्षेत्र"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","10","नागरिकता"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","11","मूल अधिकार"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","12","राज्य के नीति निर्देशक तत्व"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","13","मूल कर्तव्य"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","14","भारतीय संसद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","15","राष्ट्रपति"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","16","उपराष्ट्रपति"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","17","राज्यसभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","18","लोकसभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","19","प्रधानमंत्री"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","20","संघीय मंत्रिपरिषद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","21","संसदीय समितियां"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","22","सर्वोच्च न्यायालय"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","23","उच्च न्यायालय"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","24","राज्यपाल"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","25","मुख्यमंत्री"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","26","विधान परिषद्"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Paragraphs Constitution","27","विधानसभा"))

        }
        else if (data=="Paragraphs Science"){
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","1","गति और गति विज्ञान (Motion and Kinematics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","2","बल और गतिशीलता (Force and Dynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","3","ऊर्जा और कार्य (Energy and Work)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","4","गर्मी और ताप (Heat and Thermodynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","5","आधुनिक भौतिकी (Modern Physics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","6","विद्युत विज्ञान (Electricity and Magnetism)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","7","ध्वनि और अपवाद (Sound and Waves)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","8","प्रकाश और प्रकाशिकी (Light and Optics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","9","ऊतक संरचना और कार्य (Cell Structure and Function)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","10","प्राणियों की आनुवंशिकता (Genetics in Organisms)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","11","पारगमन और परिपाटी (Reproduction and Development)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","12","जैव एवं उनके विभाजन (Life and its Classification)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","13","संजीव प्रणाली (Ecosystem)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","14","जीवविज्ञान में शिक्षा (Education in Biology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","15","जन्तु विज्ञान (Zoology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","16","वनस्पति जीवविज्ञान (Botany)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","17","जैव-प्रौद्योगिकी (Biotechnology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","18","पर्यावरण और जीवविज्ञान (Environment and Biology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","19","रासायनिक अभिक्रिया और अभिक्रियाशास्त्र (Chemical Reactions and Stoichiometry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","20","आणविक योजना और आणविक संरचना (Atomic Structure and Chemical Bonding)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","21","अम्ल और शारीरिक रसायन (Acids and Physical Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","22","आधुनिक रासायनिक अभिक्रियाएँ (Modern Chemical Reactions)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","23","उत्तेजन (Thermodynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","24","उपचारिक रसायन (Inorganic Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","25","संघटनात्मक रसायन (Organic Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","26","अद्वितीय रसायन और संश्लेषण (Special Chemistry and Mixtures)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","27","आयनिक आणविकता (Ionic Equilibrium)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Paragraphs Science","28","उपाद्य एवं तत्त्व (Elements and Principles)"))

        }
        else if (data=="Paragraphs Economics"){
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","1","अर्थशास्त्र की परिभाषा (Definition of Economics)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","2","आय और राजस्व (Income and Revenue)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","3","उत्पादन (Production)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","4","उत्पादकता (Productivity)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","5","बाजार (Market)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","6","मूल्य निर्धारण (Price Determination)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","7","निर्यात और आयात (Export and Import)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","8","बैंकिंग और वित्तीय बाजार (Banking and Financial Market)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","9","नौकरी और बेरोजगारी (Employment and Unemployment)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","10","सामाजिक और आर्थिक न्याय (Social and Economic Justice)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","11","अधिकृत और गैर-अधिकृत बाजार (Formal and Informal Markets)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","12","आय वितरण (Income Distribution)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","13","व्यक्तिगत और सार्वजनिक खर्च (Personal and Public Expenditure)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","14","उत्पादन विकास (Production Development)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","15","नियोजन (Planning)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","16","सार्वजनिक नीति (Public Policy)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Paragraphs Economics","17","विपणन (Marketing)"))

        }
        else if (data=="Paragraphs Computer"){
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","1","कंप्यूटर का इतिहास (History of Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","2","कंप्यूटर के प्रकार (Types of Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","3","कंप्यूटर के प्रमुख अंग (Major Components of a Computer)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","4","कंप्यूटर की कार्यावस्था (Computer Operations)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","5","कंप्यूटर के ऑपरेटिंग सिस्टम (Computer Operating Systems)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","6","कंप्यूटर नेटवर्किंग (Computer Networking)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","7","कंप्यूटर के महत्वपूर्ण सॉफ़्टवेयर (Important Software Programs)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","8","कंप्यूटर सुरक्षा (Computer Security)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","9","कंप्यूटर में डेटा संरक्षण (Data Protection in Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","10","कंप्यूटर के उपयोग (Uses of Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","11","कंप्यूटर के लिए महत्वपूर्ण तकनीकी शब्दावली (Important Technical Terminology for Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","12","कंप्यूटर में अनुप्रयोग विकास (Application Development in Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","13","कंप्यूटर भाषाएँ (Computer Languages)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","14","कंप्यूटर में हार्डवेयर और सॉफ़्टवेयर (Hardware and Software in Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","15","कंप्यूटर संगणना (Computer Computing)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","16","कंप्यूटर में इंटरनेट का उपयोग (Internet Usage on Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","17","कंप्यूटर संबंधित महत्वपूर्ण वेबसाइट्स और ब्लॉग्स (Important Websites and Blogs Related to Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","18","कंप्यूटर में डिजिटल माध्यम (Digital Media on Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","19","कंप्यूटर में गतिशीलता (Computer Speed and Performance)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Paragraphs Computer","20","कंप्यूटर रिपेयर और मेंटेनेंस (Computer Repair and Maintenance)"))


        }
        else if (data=="Paragraphs Reasoning"){
            array.add(Model_for_topics(R.drawable.topic_reasoning,"Paragraphs Reasoning","1","Paragraphs Reasoning"))

        }


        //these all data for get key from adapter class and Oneline and add topics
        if (data=="Oneline History"){
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","1","अमेरिका का स्वतंत्रता संग्राम"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","2","फ्रांस की राज्यक्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","3","इटली का एकीकरण"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","4","जर्मनी का एकीकरण"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","5","रूस की क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","6","औद्योगिक क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","7","प्रथम विश्वयुद्ध"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","8","दुसरा विश्व युद्ध"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","9","बंगाल के गवर्नर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","10","भारत के गवर्नर जनरल"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","11","भारत के वायसराय"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","12","महान क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","13","सामाजिक-धार्मिक आंदोलन"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","14","आंदोलन, घटनाएं और वर्ष"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","15","स्वतंत्रता संघर्ष"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","16","प्रमुख वचन और नारे"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","17","गुलाम वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","18","खिलजी वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","19","तुगलक वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","20","धार्मिक आंदोलन"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","21","मराठा साम्राज्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","22","सिख शक्ति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","23","मराठा साम्राज्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","24","सिख शक्ति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","25","बाबर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","26","हुमायूं"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","27","अकबर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","28","जहांगीर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","29","शाहजहां"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","30","औरंगजेब"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","31","हड़प्पा सभ्यता"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","32","वैदिक साहित्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Oneline History","33","मौर्य व गुप्त काल"))


                }
        else if (data=="Oneline Geography"){
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","1","सौर मंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","2","पृथ्वी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","3","जलमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","4","झीलें"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","5","ज्वार भाटा"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","6","वायुमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","7","पवनें"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","8","पृथ्वी की संरचना"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","9","पस्थलमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","10","ज्वालामुखी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","11","पर्वत"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","12","भूकंप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","13","मरुस्थल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","14","पठार"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","15","एशिया"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","16","अफ्रीका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","17","यूरोप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","18","उत्तरी अमेरिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","19","दक्षिणी अमेरिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","20","ऑस्ट्रेलिया"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","21","अंटार्कटिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","22","विश्व के महासागर"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","23","वभारत का भूगोल सामान्य परिचय"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","24","नदियों के किनारे बसे शहर"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","25","भारत की जलवायु"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","26","भारत की नदियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","27","भारत की मिट्टियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","28","भारत की कृषि"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","29","भारत का भौतिक स्वरूप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","30","अभयारण/ राष्ट्रीय उद्यान"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","31","विश्व की प्रमुख जनजातियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","32","वराज्य और उसकी राजधानी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Oneline Geography","33","भारत में खनिज"))

                }
        else if (data=="Oneline Constitution"){
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","1","भारत का संवैधानिक इतिहास"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","2","संविधान सभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","3","संविधान की प्रस्तावना"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","4","संविधान की विशेषताएं"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","5","संविधान के स्त्रोत"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","6","संविधान के भाग"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","7","संविधान की अनुसूचियां"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","8","संविधान के अनुच्छेद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","9","संघ और उसके राज्य क्षेत्र"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","10","नागरिकता"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","11","मूल अधिकार"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","12","राज्य के नीति निर्देशक तत्व"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","13","मूल कर्तव्य"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","14","भारतीय संसद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","15","राष्ट्रपति"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","16","उपराष्ट्रपति"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","16","राज्यसभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","17","लोकसभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","18","प्रधानमंत्री"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","19","संघीय मंत्रिपरिषद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","20","संसदीय समितियां"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","21","सर्वोच्च न्यायालय"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","22","उच्च न्यायालय"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","23","राज्यपाल"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","24","मुख्यमंत्री"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","25","विधान परिषद्"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Oneline Constitution","26","विधानसभा"))

                }
        else if (data=="Oneline Science") {
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","1","गति और गति विज्ञान (Motion and Kinematics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","2","बल और गतिशीलता (Force and Dynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","3","ऊर्जा और कार्य (Energy and Work)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","4","गर्मी और ताप (Heat and Thermodynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","5","आधुनिक भौतिकी (Modern Physics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","6","विद्युत विज्ञान (Electricity and Magnetism)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","7","ध्वनि और अपवाद (Sound and Waves)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","8","प्रकाश और प्रकाशिकी (Light and Optics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","9","ऊतक संरचना और कार्य (Cell Structure and Function)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","10","प्राणियों की आनुवंशिकता (Genetics in Organisms)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","11","पारगमन और परिपाटी (Reproduction and Development)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","12","जैव एवं उनके विभाजन (Life and its Classification)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","13","संजीव प्रणाली (Ecosystem)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","14","जीवविज्ञान में शिक्षा (Education in Biology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","15","जन्तु विज्ञान (Zoology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","16","वनस्पति जीवविज्ञान (Botany)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","17","जैव-प्रौद्योगिकी (Biotechnology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","18","पर्यावरण और जीवविज्ञान (Environment and Biology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","19","रासायनिक अभिक्रिया और अभिक्रियाशास्त्र (Chemical Reactions and Stoichiometry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","20","आणविक योजना और आणविक संरचना (Atomic Structure and Chemical Bonding)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","21","अम्ल और शारीरिक रसायन (Acids and Physical Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","22","आधुनिक रासायनिक अभिक्रियाएँ (Modern Chemical Reactions)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","23","उत्तेजन (Thermodynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","24","उपचारिक रसायन (Inorganic Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","25","संघटनात्मक रसायन (Organic Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","26","अद्वितीय रसायन और संश्लेषण (Special Chemistry and Mixtures)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","27","आयनिक आणविकता (Ionic Equilibrium)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Oneline Science","28","उपाद्य एवं तत्त्व (Elements and Principles)"))

                }
        else if (data=="Oneline Economics") {
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","1","अर्थशास्त्र की परिभाषा (Definition of Economics)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","2","आय और राजस्व (Income and Revenue)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","3","उत्पादन (Production)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","4","उत्पादकता (Productivity)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","5","बाजार (Market)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","6","मूल्य निर्धारण (Price Determination)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","7","निर्यात और आयात (Export and Import)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","8","बैंकिंग और वित्तीय बाजार (Banking and Financial Market)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","9","नौकरी और बेरोजगारी (Employment and Unemployment)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","10","सामाजिक और आर्थिक न्याय (Social and Economic Justice)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","11","अधिकृत और गैर-अधिकृत बाजार (Formal and Informal Markets)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","12","आय वितरण (Income Distribution)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","13","व्यक्तिगत और सार्वजनिक खर्च (Personal and Public Expenditure)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","14","उत्पादन विकास (Production Development)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","15","नियोजन (Planning)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","16","सार्वजनिक नीति (Public Policy)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Oneline Economics","17","विपणन (Marketing)"))

                }
        else if (data=="Oneline Computer") {
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","1","कंप्यूटर का इतिहास (History of Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","2","कंप्यूटर के प्रकार (Types of Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","3","कंप्यूटर के प्रमुख अंग (Major Components of a Computer)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","4","कंप्यूटर की कार्यावस्था (Computer Operations)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","5","कंप्यूटर के ऑपरेटिंग सिस्टम (Computer Operating Systems)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","6","कंप्यूटर नेटवर्किंग (Computer Networking)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","7","कंप्यूटर के महत्वपूर्ण सॉफ़्टवेयर (Important Software Programs)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","8","कंप्यूटर सुरक्षा (Computer Security)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","9","कंप्यूटर में डेटा संरक्षण (Data Protection in Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","10","कंप्यूटर के उपयोग (Uses of Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","11","कंप्यूटर के लिए महत्वपूर्ण तकनीकी शब्दावली (Important Technical Terminology for Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","12","कंप्यूटर में अनुप्रयोग विकास (Application Development in Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","13","कंप्यूटर भाषाएँ (Computer Languages)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","14","कंप्यूटर में हार्डवेयर और सॉफ़्टवेयर (Hardware and Software in Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","15","कंप्यूटर संगणना (Computer Computing)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","16","कंप्यूटर में इंटरनेट का उपयोग (Internet Usage on Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","17","कंप्यूटर संबंधित महत्वपूर्ण वेबसाइट्स और ब्लॉग्स (Important Websites and Blogs Related to Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","18","कंप्यूटर में डिजिटल माध्यम (Digital Media on Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","19","कंप्यूटर में गतिशीलता (Computer Speed and Performance)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Oneline Computer","20","कंप्यूटर रिपेयर और मेंटेनेंस (Computer Repair and Maintenance)"))


        }
        else if (data=="Oneline Reasoning"){
                    array.add(Model_for_topics(R.drawable.topic_reasoning,"Oneline Reasoning","1","Oneline Reasoning"))

                }

        //these all data for get key from adapter class and Quiz and add topics
        if (data=="Quiz History"){
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","1","अमेरिका का स्वतंत्रता संग्राम"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","2","फ्रांस की राज्यक्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","3","इटली का एकीकरण"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","4","जर्मनी का एकीकरण"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","5","रूस की क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","6","औद्योगिक क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","7","प्रथम विश्वयुद्ध"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","8","दुसरा विश्व युद्ध"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","9","बंगाल के गवर्नर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","10","भारत के गवर्नर जनरल"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","11","भारत के वायसराय"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","12","महान क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","13","सामाजिक-धार्मिक आंदोलन"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","14","आंदोलन, घटनाएं और वर्ष"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","15","स्वतंत्रता संघर्ष"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","16","प्रमुख वचन और नारे"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","17","गुलाम वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","18","खिलजी वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","19","तुगलक वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","20","धार्मिक आंदोलन"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","21","मराठा साम्राज्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","22","सिख शक्ति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","23","मराठा साम्राज्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","24","सिख शक्ति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","25","बाबर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","26","हुमायूं"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","27","अकबर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","28","जहांगीर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","29","शाहजहां"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","30","औरंगजेब"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","31","हड़प्पा सभ्यता"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","32","वैदिक साहित्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Quiz History","33","मौर्य व गुप्त काल"))
                }
        else if (data=="Quiz Geography"){
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","1","सौर मंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","2","पृथ्वी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","3","जलमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","4","झीलें"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","5","ज्वार भाटा"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","6","वायुमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","7","पवनें"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","8","पृथ्वी की संरचना"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","9","पस्थलमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","10","ज्वालामुखी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","11","पर्वत"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","12","भूकंप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","13","मरुस्थल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","14","पठार"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","15","एशिया"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","16","अफ्रीका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","17","यूरोप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","18","उत्तरी अमेरिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","19","दक्षिणी अमेरिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","20","ऑस्ट्रेलिया"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","21","अंटार्कटिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","22","विश्व के महासागर"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","23","वभारत का भूगोल सामान्य परिचय"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","24","नदियों के किनारे बसे शहर"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","25","भारत की जलवायु"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","26","भारत की नदियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","27","भारत की मिट्टियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","28","भारत की कृषि"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","29","भारत का भौतिक स्वरूप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","30","अभयारण/ राष्ट्रीय उद्यान"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","31","विश्व की प्रमुख जनजातियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","32","वराज्य और उसकी राजधानी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Quiz Geography","33","भारत में खनिज"))

                }
        else if (data=="Quiz Constitution"){
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","1","भारत का संवैधानिक इतिहास"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","2","संविधान सभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","3","संविधान की प्रस्तावना"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","4","संविधान की विशेषताएं"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","5","संविधान के स्त्रोत"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","6","संविधान के भाग"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","7","संविधान की अनुसूचियां"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","8","संविधान के अनुच्छेद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","9","संघ और उसके राज्य क्षेत्र"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","10","नागरिकता"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","11","मूल अधिकार"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","12","राज्य के नीति निर्देशक तत्व"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","13","मूल कर्तव्य"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","14","भारतीय संसद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","15","राष्ट्रपति"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","16","उपराष्ट्रपति"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","16","राज्यसभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","17","लोकसभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","18","प्रधानमंत्री"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","19","संघीय मंत्रिपरिषद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","20","संसदीय समितियां"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","21","सर्वोच्च न्यायालय"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","22","उच्च न्यायालय"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","23","राज्यपाल"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","24","मुख्यमंत्री"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","25","विधान परिषद्"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Quiz Constitution","26","विधानसभा"))

                }
        else if (data=="Quiz Science"){
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","1","गति और गति विज्ञान (Motion and Kinematics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","2","बल और गतिशीलता (Force and Dynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","3","ऊर्जा और कार्य (Energy and Work)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","4","गर्मी और ताप (Heat and Thermodynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","5","आधुनिक भौतिकी (Modern Physics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","6","विद्युत विज्ञान (Electricity and Magnetism)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","7","ध्वनि और अपवाद (Sound and Waves)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","8","प्रकाश और प्रकाशिकी (Light and Optics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","9","ऊतक संरचना और कार्य (Cell Structure and Function)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","10","प्राणियों की आनुवंशिकता (Genetics in Organisms)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","11","पारगमन और परिपाटी (Reproduction and Development)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","12","जैव एवं उनके विभाजन (Life and its Classification)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","13","संजीव प्रणाली (Ecosystem)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","14","जीवविज्ञान में शिक्षा (Education in Biology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","15","जन्तु विज्ञान (Zoology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","16","वनस्पति जीवविज्ञान (Botany)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","17","जैव-प्रौद्योगिकी (Biotechnology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","18","पर्यावरण और जीवविज्ञान (Environment and Biology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","19","रासायनिक अभिक्रिया और अभिक्रियाशास्त्र (Chemical Reactions and Stoichiometry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","20","आणविक योजना और आणविक संरचना (Atomic Structure and Chemical Bonding)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","21","अम्ल और शारीरिक रसायन (Acids and Physical Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","22","आधुनिक रासायनिक अभिक्रियाएँ (Modern Chemical Reactions)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","23","उत्तेजन (Thermodynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","24","उपचारिक रसायन (Inorganic Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","25","संघटनात्मक रसायन (Organic Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","26","अद्वितीय रसायन और संश्लेषण (Special Chemistry and Mixtures)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","27","आयनिक आणविकता (Ionic Equilibrium)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Quiz Science","28","उपाद्य एवं तत्त्व (Elements and Principles)"))

                }
        else if (data=="Quiz Economics"){
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","1","अर्थशास्त्र की परिभाषा (Definition of Economics)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","2","आय और राजस्व (Income and Revenue)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","3","उत्पादन (Production)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","4","उत्पादकता (Productivity)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","5","बाजार (Market)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","6","मूल्य निर्धारण (Price Determination)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","7","निर्यात और आयात (Export and Import)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","8","बैंकिंग और वित्तीय बाजार (Banking and Financial Market)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","9","नौकरी और बेरोजगारी (Employment and Unemployment)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","10","सामाजिक और आर्थिक न्याय (Social and Economic Justice)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","11","अधिकृत और गैर-अधिकृत बाजार (Formal and Informal Markets)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","12","आय वितरण (Income Distribution)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","13","व्यक्तिगत और सार्वजनिक खर्च (Personal and Public Expenditure)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","14","उत्पादन विकास (Production Development)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","15","नियोजन (Planning)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","16","सार्वजनिक नीति (Public Policy)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Quiz Economics","17","विपणन (Marketing)"))

                }
        else if (data=="Quiz Computer"){
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","1","कंप्यूटर का इतिहास (History of Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","2","कंप्यूटर के प्रकार (Types of Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","3","कंप्यूटर के प्रमुख अंग (Major Components of a Computer)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","4","कंप्यूटर की कार्यावस्था (Computer Operations)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","5","कंप्यूटर के ऑपरेटिंग सिस्टम (Computer Operating Systems)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","6","कंप्यूटर नेटवर्किंग (Computer Networking)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","7","कंप्यूटर के महत्वपूर्ण सॉफ़्टवेयर (Important Software Programs)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","8","कंप्यूटर सुरक्षा (Computer Security)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","9","कंप्यूटर में डेटा संरक्षण (Data Protection in Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","10","कंप्यूटर के उपयोग (Uses of Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","11","कंप्यूटर के लिए महत्वपूर्ण तकनीकी शब्दावली (Important Technical Terminology for Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","12","कंप्यूटर में अनुप्रयोग विकास (Application Development in Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","13","कंप्यूटर भाषाएँ (Computer Languages)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","14","कंप्यूटर में हार्डवेयर और सॉफ़्टवेयर (Hardware and Software in Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","15","कंप्यूटर संगणना (Computer Computing)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","16","कंप्यूटर में इंटरनेट का उपयोग (Internet Usage on Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","17","कंप्यूटर संबंधित महत्वपूर्ण वेबसाइट्स और ब्लॉग्स (Important Websites and Blogs Related to Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","18","कंप्यूटर में डिजिटल माध्यम (Digital Media on Computers)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","19","कंप्यूटर में गतिशीलता (Computer Speed and Performance)"))
            array.add(Model_for_topics(R.drawable.topic_computer,"Quiz Computer","20","कंप्यूटर रिपेयर और मेंटेनेंस (Computer Repair and Maintenance)"))


        }
        else if (data=="Quiz Reasoning"){
                    array.add(Model_for_topics(R.drawable.topic_reasoning,"Quiz Reasoning","1","Quiz Reasoning"))

                }

        //these all data for get key from adapter class and Trick and add topics
        if (data=="Trick History"){
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","1","अमेरिका का स्वतंत्रता संग्राम"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","2","फ्रांस की राज्यक्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","3","इटली का एकीकरण"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","4","जर्मनी का एकीकरण"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","5","रूस की क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","6","औद्योगिक क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","7","प्रथम विश्वयुद्ध"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","8","दुसरा विश्व युद्ध"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","9","बंगाल के गवर्नर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","10","भारत के गवर्नर जनरल"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","11","भारत के वायसराय"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","12","महान क्रांति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","13","सामाजिक-धार्मिक आंदोलन"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","14","आंदोलन, घटनाएं और वर्ष"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","15","स्वतंत्रता संघर्ष"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","16","प्रमुख वचन और नारे"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","17","गुलाम वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","18","खिलजी वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","19","तुगलक वंश"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","20","धार्मिक आंदोलन"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","21","मराठा साम्राज्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","22","सिख शक्ति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","23","मराठा साम्राज्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","24","सिख शक्ति"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","25","बाबर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","26","हुमायूं"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","27","अकबर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","28","जहांगीर"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","29","शाहजहां"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","30","औरंगजेब"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","31","हड़प्पा सभ्यता"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","32","वैदिक साहित्य"))
            array.add(Model_for_topics(R.drawable.topic_history1,"Trick History","33","मौर्य व गुप्त काल"))
                }
        else if (data=="Trick Geography"){
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","1","सौर मंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","2","पृथ्वी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","3","जलमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","4","झीलें"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","5","ज्वार भाटा"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","6","वायुमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","7","पवनें"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","8","पृथ्वी की संरचना"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","9","पस्थलमंडल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","10","ज्वालामुखी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","11","पर्वत"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","12","भूकंप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","13","मरुस्थल"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","14","पठार"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","15","एशिया"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","16","अफ्रीका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","17","यूरोप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","18","उत्तरी अमेरिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","19","दक्षिणी अमेरिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","20","ऑस्ट्रेलिया"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","21","अंटार्कटिका"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","22","विश्व के महासागर"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","23","वभारत का भूगोल सामान्य परिचय"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","24","नदियों के किनारे बसे शहर"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","25","भारत की जलवायु"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","26","भारत की नदियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","27","भारत की मिट्टियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","28","भारत की कृषि"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","29","भारत का भौतिक स्वरूप"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","30","अभयारण/ राष्ट्रीय उद्यान"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","31","विश्व की प्रमुख जनजातियां"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","32","वराज्य और उसकी राजधानी"))
            array.add(Model_for_topics(R.drawable.topic_geography1,"Trick Geography","33","भारत में खनिज"))

                }
        else if (data=="Trick Constitution"){
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","1","भारत का संवैधानिक इतिहास"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","2","संविधान सभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","3","संविधान की प्रस्तावना"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","4","संविधान की विशेषताएं"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","5","संविधान के स्त्रोत"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","6","संविधान के भाग"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","7","संविधान की अनुसूचियां"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","8","संविधान के अनुच्छेद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","9","संघ और उसके राज्य क्षेत्र"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","10","नागरिकता"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","11","मूल अधिकार"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","12","राज्य के नीति निर्देशक तत्व"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","13","मूल कर्तव्य"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","14","भारतीय संसद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","15","राष्ट्रपति"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","16","उपराष्ट्रपति"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","16","राज्यसभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","17","लोकसभा"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","18","प्रधानमंत्री"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","19","संघीय मंत्रिपरिषद"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","20","संसदीय समितियां"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","21","सर्वोच्च न्यायालय"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","22","उच्च न्यायालय"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","23","राज्यपाल"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","24","मुख्यमंत्री"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","25","विधान परिषद्"))
            array.add(Model_for_topics(R.drawable.topic_constitution1,"Trick Constitution","26","विधानसभा"))

                }
        else if (data=="Trick Science"){
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","1","गति और गति विज्ञान (Motion and Kinematics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","2","बल और गतिशीलता (Force and Dynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","3","ऊर्जा और कार्य (Energy and Work)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","4","गर्मी और ताप (Heat and Thermodynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","5","आधुनिक भौतिकी (Modern Physics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","6","विद्युत विज्ञान (Electricity and Magnetism)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","7","ध्वनि और अपवाद (Sound and Waves)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","8","प्रकाश और प्रकाशिकी (Light and Optics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","9","ऊतक संरचना और कार्य (Cell Structure and Function)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","10","प्राणियों की आनुवंशिकता (Genetics in Organisms)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","11","पारगमन और परिपाटी (Reproduction and Development)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","12","जैव एवं उनके विभाजन (Life and its Classification)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","13","संजीव प्रणाली (Ecosystem)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","14","जीवविज्ञान में शिक्षा (Education in Biology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","15","जन्तु विज्ञान (Zoology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","16","वनस्पति जीवविज्ञान (Botany)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","17","जैव-प्रौद्योगिकी (Biotechnology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","18","पर्यावरण और जीवविज्ञान (Environment and Biology)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","19","रासायनिक अभिक्रिया और अभिक्रियाशास्त्र (Chemical Reactions and Stoichiometry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","20","आणविक योजना और आणविक संरचना (Atomic Structure and Chemical Bonding)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","21","अम्ल और शारीरिक रसायन (Acids and Physical Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","22","आधुनिक रासायनिक अभिक्रियाएँ (Modern Chemical Reactions)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","23","उत्तेजन (Thermodynamics)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","24","उपचारिक रसायन (Inorganic Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","25","संघटनात्मक रसायन (Organic Chemistry)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","26","अद्वितीय रसायन और संश्लेषण (Special Chemistry and Mixtures)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","27","आयनिक आणविकता (Ionic Equilibrium)"))
            array.add(Model_for_topics(R.drawable.topic_science1,"Trick Science","28","उपाद्य एवं तत्त्व (Elements and Principles)"))

                }
        else if (data=="Trick Economics"){
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","1","अर्थशास्त्र की परिभाषा (Definition of Economics)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","2","आय और राजस्व (Income and Revenue)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","3","उत्पादन (Production)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","4","उत्पादकता (Productivity)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","5","बाजार (Market)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","6","मूल्य निर्धारण (Price Determination)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","7","निर्यात और आयात (Export and Import)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","8","बैंकिंग और वित्तीय बाजार (Banking and Financial Market)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","9","नौकरी और बेरोजगारी (Employment and Unemployment)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","10","सामाजिक और आर्थिक न्याय (Social and Economic Justice)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","11","अधिकृत और गैर-अधिकृत बाजार (Formal and Informal Markets)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","12","आय वितरण (Income Distribution)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","13","व्यक्तिगत और सार्वजनिक खर्च (Personal and Public Expenditure)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","14","उत्पादन विकास (Production Development)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","15","नियोजन (Planning)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","16","सार्वजनिक नीति (Public Policy)"))
            array.add(Model_for_topics(R.drawable.topic_economic3,"Trick Economics","17","विपणन (Marketing)"))

                }
        else if (data=="Trick Computer"){
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","1","कंप्यूटर का इतिहास (History of Computers)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","2","कंप्यूटर के प्रकार (Types of Computers)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","3","कंप्यूटर के प्रमुख अंग (Major Components of a Computer)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","4","कंप्यूटर की कार्यावस्था (Computer Operations)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","5","कंप्यूटर के ऑपरेटिंग सिस्टम (Computer Operating Systems)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","6","कंप्यूटर नेटवर्किंग (Computer Networking)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","7","कंप्यूटर के महत्वपूर्ण सॉफ़्टवेयर (Important Software Programs)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","8","कंप्यूटर सुरक्षा (Computer Security)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","9","कंप्यूटर में डेटा संरक्षण (Data Protection in Computers)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","10","कंप्यूटर के उपयोग (Uses of Computers)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","11","कंप्यूटर के लिए महत्वपूर्ण तकनीकी शब्दावली (Important Technical Terminology for Computers)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","12","कंप्यूटर में अनुप्रयोग विकास (Application Development in Computers)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","13","कंप्यूटर भाषाएँ (Computer Languages)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","14","कंप्यूटर में हार्डवेयर और सॉफ़्टवेयर (Hardware and Software in Computers)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","15","कंप्यूटर संगणना (Computer Computing)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","16","कंप्यूटर में इंटरनेट का उपयोग (Internet Usage on Computers)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","17","कंप्यूटर संबंधित महत्वपूर्ण वेबसाइट्स और ब्लॉग्स (Important Websites and Blogs Related to Computers)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","18","कंप्यूटर में डिजिटल माध्यम (Digital Media on Computers)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","19","कंप्यूटर में गतिशीलता (Computer Speed and Performance)"))
                    array.add(Model_for_topics(R.drawable.topic_computer,"Trick Computer","20","कंप्यूटर रिपेयर और मेंटेनेंस (Computer Repair and Maintenance)"))

                }
        else if (data=="Trick Reasoning"){
                    array.add(Model_for_topics(R.drawable.topic_reasoning,"Trick Reasoning","1","Trick Reasoning"))

                }


    }
}